spring:
  application:
    name: datn

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/datn}
    username: ${DB_USERNAME:postgres_user}
    password: ${DB_PASSWORD:postgres_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create, update, validate, or none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
